version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8090:8090
    environment:
      KRAKEN_HOST: "https://api.kraken.com"
      HTTP_ADDR: ":8090"
      DEBUG_ERRORS: 1
    command: ["./app"]